name: Build-PCSX2-iOS
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Dependencies
        run: brew install cmake ninja pkg-config

      - name: Configure and Build
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_OSX_SYSROOT=iphoneos \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DENABLE_TESTS=OFF \
            -DUSE_VULKAN=OFF
          cmake --build build --config Release

